kubernetesAPI: https://kubernetes.svc
clusterName: dev
# TODO: This might be a nice to have feature
# excludeOpenShift: true

cronJob:
  image: registry.redhat.io/openshift4/ose-cli:v4.10
  name: vault-role-namespace-sync
  schedule: "*/1 * * * *"
  script: |
    #!/bin/bash
    echo "Hello test!"
