apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-role-namespace-sync
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: "{{ .Values.cronJob.image }}"
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - /tmp/scripts/vault-role-namespace-sync.sh
            volumeMounts:
            - name: vault-role-namespace-sync
              mountPath: /tmp/scripts/vault-role-namespace-sync.sh
              subPath: vault-role-namespace-sync.sh
          restartPolicy: OnFailure
          volumes:
          - name: vault-role-namespace-sync
            configMap:
              name: vault-role-namespace-sync
              defaultMode: 0755
