{{ if .Values.kubernetes.createRole }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-role-namespace-sync
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vault-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-namespaces
{{ end }}
